export const mediaList = [
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
    {
        name: 'Bảng Xếp Hạng Light Novel Việt Nam',
        username: 'sample',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Tôi không phải là lolicon, chỉ là cô gái tôi thích tình cờ lại là loli.',
    },
];
