export const mediaList = [
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
    {
        name: 'Light Novel Việt Nam Fanpage',
        username: 'username',
        url: 'https://facebook.com',
        avatar: 'https://yt3.ggpht.com/yti/AGOGRCpP0MYQ6pqgZiPwxTzSgKGnUdsCZagtWQss9eJwNQ=s108-c-k-c0x00ffffff-no-rj',
        description: 'Premium PR Pack has been activated!',
    },
];
